version: '2'
networks:
  basic:
    driver:
      bridge
volumes:
  db:
    driver: local

services:
  nginx:
    networks:
      - basic
    build:
      dockerfile: Dockerfile-nginx
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - fpm
  fpm:
    networks:
      - basic
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    build:
      context: .
      dockerfile: Dockerfile-fpm
    links:
      - db
  db:
    networks:
      - basic  
    image: mysql:5.7.17
    links:
      - myadmin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: calculator
      MYSQL_DATABASE: calculator
      MYSQL_USER: calculator
      MYSQL_PASSWORD: calculator
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      #- "./data/mysql:/var/lib/mysql"
  myadmin:
    networks:
      - basic
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: calculator      
      MYSQL_USER: calculator
      MYSQL_PASSWORD: calculator

